---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespaces.yaml
  - ./cert-manager/
  - ./traefik/
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.18.1/cnpg-1.18.1.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
  - ./prometheus/
