apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager-controller
          ports:
            - containerPort: 9402
              name: http
              protocol: TCP
          args:
          - --dns01-recursive-nameservers-only=true
          - --dns01-recursive-nameservers=9.9.9.9:53,8.8.8.8:53,1.1.1.1:53
