---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.20.0/cnpg-1.20.0.yaml
